version: "3.7"
services:
  streaming:
    image: alpine:3.14.1
    container_name: streaming
    volumes:
      - ./script:/script
      - ./input:/data/input
      - ./output:/data/output
    command: "sh -c 'cd /script && chmod +x streaming.sh && sh streaming.sh'"
